### ISSUE TITLE
[Bug] Profile loads multiple times

### ISSUE THREAD

**Issue by P6g9YHK6** [CrazyWolf13/unix-pwsh#2]
everything works fine on my desktop but on my laptop the profile loads 3 times every time i launch the terminal
it loads once then it looks like it clears the terminal then load twice as per the screenshot.

![image](https://github.com/user-attachments/assets/fecd4318-430c-42ee-8a55-3a98a71ce813)

i already cleared the folder to try to fix it

**Comment by CrazyWolf13** [comment]
Hi
Can't seem to replicate this, can you send the contents of $PROFILE?

**Comment by P6g9YHK6** [comment]
it was in the screen shot it is just the plain config.

```
if (Test-Path (Join-Path -Path $env:USERPROFILE -ChildPath "unix-pwsh\Microsoft.PowerShell_profile.ps1")) { . (Join-Path -Path $env:USERPROFILE -ChildPath  "unix-pwsh\Microsoft.PowerShell_profile.ps1") } else { iex (iwr "https://raw.githubusercontent.com/CrazyWolf13/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content }

#f45873b3-b655-43a6-b217-97c00aa0db58 PowerToys CommandNotFound module

Import-Module -Name Microsoft.WinGet.CommandNotFound
#f45873b3-b655-43a6-b217-97c00aa0db58
```

**Comment by CrazyWolf13** [comment]
Hmm, that's weird, are you fully only and able to ping raw.githubusercontent.com ?

Have you tried removing the OLD powershell profile (not poershell 7.x $PROFILE) and also fully removing the new $PROFILE with the unix-pwsh folder.

**Comment by P6g9YHK6** [comment]
Closing indeed manually cleaning all profiles worked
for future referance:

`Get-ChildItem $PROFILE.AllUsersCurrentHost, $PROFILE.AllUsersAllHosts, $PROFILE.CurrentUserCurrentHost, $PROFILE.CurrentUserAllHosts | Select-Object FullName`
