### ISSUE TITLE
[Feature request] Automate Microsoft.WinGet.CommandNotFound installation

### ISSUE THREAD

**Issue by P6g9YHK6** [CrazyWolf13/unix-pwsh#3]
https://www.powershellgallery.com/packages/Microsoft.WinGet.CommandNotFound/1.0.4.0

Powertoys instruction could be skipped with a direct installation

**Comment by CrazyWolf13** [comment]
Ahhh finlly, previously it was not avaiable anywhere, so I could not install it normally, thanks will fix :)

**Comment by CrazyWolf13** [comment]
Just fixed :)
