### ISSUE TITLE
[Feature Request] add a sudo installation prompt to the initial setup

### ISSUE THREAD

**Issue by P6g9YHK6** [CrazyWolf13/unix-pwsh#4]
I propose adding https://github.com/gerardog/gsudo to the initial setup if no "sudo" command is found on the system

i suppose that the prompt could also propose to enable the native windows option if available but i can't really test this as i don't have a compatible device.

Exemple code :
```
# Check if 'sudo' command is available
if (!(Get-Command sudo -ErrorAction SilentlyContinue)) {
    Write-Host "'gsudo' not found. Installing 'gsudo'..."

    # install Gsudo
    winget install gerardog.gsudo

    # Verify installation
    if (Get-Command sudo -ErrorAction SilentlyContinue) {
        Write-Host "'gsudo' installed successfully."
    } else {
        Write-Host "Installation failed."
    }
} else {
    Write-Host "'gsudo' is already installed."
}

```

**Comment by CrazyWolf13** [comment]
Thanks for the suggestion, I like it :)

When installing the profile, it will now ask if no sudo found :)
Huge thanks for the feedback and improvement ideas btw ☺️

Would you be interested in chatting a bit on improvements via matrix? (crazywolf13@matrix.org)

**Comment by P6g9YHK6** [comment]
> Thanks for the suggestion, I like it :)
> 
> When installing the profile, it will now ask if no sudo found :) Huge thanks for the feedback and improvement ideas btw ☺️
> 
> Would you be interested in chatting a bit on improvements via matrix? ([crazywolf13@matrix.org](mailto:crazywolf13@matrix.org))

added matrix.
