### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by Peter-Go** [CrazyWolf13/unix-pwsh#6]
Hello,

I forked the repo and edited the Microsoft.PowerShell_profile.ps1 to have my github username but when I run the command:

`iex (iwr "https://raw.githubusercontent.com/<myUser>/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content`

The PowerShell window closes, when I reopen the prompt is the same and the Microsoft.PowerShell_profile.ps1 is blank.

`Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`

Is there a log to check why this is failling?

**Comment by CrazyWolf13** [comment]
Hi
Thanks for using my dotfiles as source :)

Hmm yeah there should be definitely something in your profile file, can you check with
```cat $PROFILE``` ?

Also when removing the unix-pwsh folder from your userprofile folder, and entering the above iex command again, can you spot any obious red errors?

Are you sure you are using the correct profile in windows terminal or similar?

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Peter-Go** [comment]
Hello, 

The unix-pwsh folder doesn't get created when running the iex command, should the 

PS  > cat $PROFILE
Get-Content: Cannot find path 'C:\Users\Peter-go\Documents\PowerShell\Microsoft.PowerShell_profile.ps1' because it does not exist.
PS  > New-Item -Path "C:\Users\Peter-Go\Documents\PowerShell\Microsoft.PowerShell_profile.ps1" -ItemType File
PS  > cat $PROFILE
PS  > iex (iwr "https://raw.githubusercontent.com/Peter-Go/unix-pwsh/main/Microsoft.PowerShell_profile.ps1").Content

PowerShell window closes


This is running PowerShell 7 x64 although the same issue occurs in terminal running PowerShell 7

**Comment by CrazyWolf13** [comment]
hmm that seems very weird, seems like the script isn't correctly fetching at all!

That is really odd, I can test your config and it seems to work absolutely fine for me:

![grafik](https://github.com/user-attachments/assets/5d502774-d5bf-49ba-be81-dcf53c36c067)

Can you see such an installation process when entering that command?

or could you share a video when executing?

I have decided not to build in any logging, as it would take up a way too big amount and also create unncessary overhead in loading times while a profile should be loading as fast as possible.

What is your execution-policy in powershell?

**Comment by Peter-Go** [comment]
It must be my machine, I am doing ssl inspection on web traffic so I can
disable that and reattempt

**Comment by CrazyWolf13** [comment]
Hi
Were you able to resolve the issue?

**Comment by Peter-Go** [comment]
Yes it was SSL inspection, it through me as there was no error message.

Working fine now 🙂

Thanks for the help
